GoltaraSoft.SpaWeb.Web/Controllers/ClienteController.cs
using AutoMapper;
using GoltaraSolutions.SpaWeb.Web.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using GoltaraSolutions.Common.Extensions;
using GoltaraSolutions.SpaWeb.Domain.AgendaContext.Atendimento;
using GoltaraSolutions.SpaWeb.Domain.ClienteContext;
using GoltaraSolutions.SpaWeb.Domain.ClienteContext;
using GoltaraSolutions.SpaWeb.Domain.FuncionarioContext;
using GoltaraSolutions.SpaWeb.Domain.ServicoContext;
using GoltaraSoft.SysBeauty.Web.Controllers;
using GoltaraSolutions.SpaWeb.Domain.EmpresaContext;
using GoltaraSolutions.SpaWeb.Domain.AgendaContext.Atendimento.ReportViews;
using GoltaraSolutions.Common.Domain.Report;

namespace GoltaraSolutions.SpaWeb.Web.Controllers
{
    [Authorize()]
    public class ClienteController : BaseController
    {
        private ClienteDomainServices sv;
        private OrigemDomainServices svOrigem;
        private AtendimentoDomainServices svAtendimento;
        private IMapper _mapp;
        public ClienteController(ClienteDomainServices clienteDomainServices,
            OrigemDomainServices origemDomainServices,
            AtendimentoDomainServices atendimentoDomainServices)
        {
            sv = clienteDomainServices;
            svOrigem = origemDomainServices;
            svAtendimento = atendimentoDomainServices;

            MapperConfiguration config = new MapperConfiguration(cfg =>
           {
               cfg.CreateMap<ClienteViewModel, ClienteModel>();
               cfg.CreateMap<AtendimentoModel, AtendimentoViewModel>();
               cfg.CreateMap<ClienteModel, ClienteViewModel>()
                .ForMember(dest => dest.Ativo, opt => opt.MapFrom(src => (!src.Deletado).ToCustomString()))
                .ForMember(dest => dest.Origens, opt => opt.Ignore())
                .ForMember(dest => dest.OrigemSelecionada, opt => opt.Ignore()); ;
           });

            _mapp = config.CreateMapper();
        }
        // GET: Cliente
        public ActionResult Index(string tipo)
        {
            List<ClienteModel> listModel = sv.List(UsuarioLogado.IdEmpresa).ToList();
            List<ClienteViewModel> listView = new List<ClienteViewModel>();

            switch (tipo)
            {
                case "Ativos":
                    listModel = listModel.Where(i => i.Deletado == false).ToList();
                    ViewBag.Filtro = "Ativos";

                    break;
                case "Inativos":
                    listModel = listModel.Where(i => i.Deletado == true).ToList();
                    ViewBag.Filtro = "Inativos";

                    break;
                case "Todos":
                    listModel = listModel.ToList();
                    ViewBag.Filtro = "Todos";

                    break;
                default:
                    listModel = listModel.Where(i => i.Deletado == false).ToList();
                    ViewBag.Filtro = "Ativos";

                    break;
            }

            listModel.ForEach(x =>
            {
                ClienteViewModel cliView = _mapp.Map<ClienteViewModel>(x);
                OrigemModel Origem = svOrigem.Find(x.IdOrigem);
                if (Origem.IsNotNull())
                    cliView.Origem = Origem;
                listView.Add(cliView);
            }
            );

            return View(listView);
        }

        // GET: Cliente/Details/5
        public ActionResult Details(long id)
        {
            ClienteModel Cliente = sv.Find(id);
            ClienteViewModel ClienteView = _mapp.Map<ClienteViewModel>(Cliente);

            List<FiltrosReportView> Origens = svOrigem.ListarFiltro(UsuarioLogado.IdEmpresa).ToList();
            ClienteView.Origens = new SelectList(Origens, "Id", "Nome");
            ClienteView.OrigemSelecionada = Cliente.IdOrigem;

            OrigemModel Origem = svOrigem.Find(Cliente.IdOrigem);
            if (Origem.IsNotNull())
                ClienteView.Origem = Origem;

            List<AtendimentoReportView> atendimentos = svAtendimento.Relatorio(UsuarioLogado.IdEmpresa, DateTime.Now.AddMonths(-6).FirstDayOfMonth(),
                DateTime.Now.LastHourOfDay(),
                id,
                null,
                null,
                null,
                null,
                null);

            //List<AtendimentoViewModel> listView = new List<AtendimentoViewModel>();
            //if (atendimentos.IsNotNull())
            //{
            //    atendimentos.ForEach(o => listView.Add(_mapp.Map<AtendimentoViewModel>(o)));
            //}

            ClienteView.Historico = atendimentos;

            return View(ClienteView);
        }

        // GET: Cliente/Create
        public ActionResult Create()
        {
            ClienteViewModel Cliente = new ClienteViewModel();

            List<FiltrosReportView> Origens = svOrigem.ListarFiltro(UsuarioLogado.IdEmpresa).ToList();
            Cliente.Origens = new SelectList(Origens, "Id", "Nome");

            return View(Cliente);
        }

        // POST: Cliente/Create
        [HttpPost]
        public ActionResult Create(ClienteViewModel objeto)
        {
            try
            {
                
                sv.Cadastrar(UsuarioLogado.IdEmpresa, objeto.Nome, objeto.DataNascimento, objeto.Telefone, objeto.Celular, objeto.Email, objeto.Sexo, objeto.OrigemSelecionada);

                TempData["Nome"] = objeto.Nome;
                TempData["Acao"] = "criado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);

                return Create();
            }
        }

        // GET: Cliente/Edit/5
        public ActionResult Edit(long id)
        {
            ClienteModel Cliente = sv.Find(id);
            ClienteViewModel ClienteView = _mapp.Map<ClienteViewModel>(Cliente);

            List<FiltrosReportView> Origens = svOrigem.ListarFiltro(UsuarioLogado.IdEmpresa).ToList();
            ClienteView.Origens = new SelectList(Origens, "Id", "Nome");
            ClienteView.OrigemSelecionada = Cliente.IdOrigem;

            OrigemModel Origem = svOrigem.Find(Cliente.IdOrigem);
            if (Origem.IsNotNull())
                ClienteView.Origem = Origem;

            return View(ClienteView);
        }

        // POST: Cliente/Edit/5
        [HttpPost]
        public ActionResult Edit(long id, ClienteViewModel objeto)
        {
            try
            {
                
                sv.Editar(objeto.Id, objeto.Nome, objeto.DataNascimento, objeto.Telefone, objeto.Celular, objeto.Email, objeto.Sexo, objeto.OrigemSelecionada);

                TempData["Nome"] = objeto.Nome;
                TempData["Acao"] = "editado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);


                ClienteModel Cliente = sv.Find(id);
                ClienteViewModel ClienteView = _mapp.Map<ClienteViewModel>(Cliente);

                List<FiltrosReportView> Origens = svOrigem.ListarFiltro(UsuarioLogado.IdEmpresa).ToList();
                ClienteView.Origens = new SelectList(Origens, "Id", "Nome");
                ClienteView.OrigemSelecionada = Cliente.IdOrigem;

                OrigemModel Origem = svOrigem.Find(Cliente.IdOrigem);
                if (Origem.IsNotNull())
                    ClienteView.Origem = Origem;

                return View(ClienteView);
            }
        }

        // GET: Cliente/Delete/5
        public ActionResult Delete(long id)
        {
            ClienteModel Cliente = sv.Find(id);

            return View(_mapp.Map<ClienteViewModel>(Cliente));
        }

        // POST: Cliente/Delete/5
        [HttpPost]
        public ActionResult Delete(long id, ClienteViewModel objeto)
        {
            try
            {
                
                sv.Delete(id);

                ClienteModel c = sv.Find(id);

                TempData["Nome"] = c.Nome;
                TempData["Acao"] = "desativado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View();
            }
        }

        // GET: Cliente/Recover/5
        public ActionResult Recover(long id)
        {
            ClienteModel Cliente = sv.Find(id);

            return View(_mapp.Map<ClienteViewModel>(Cliente));
        }

        // POST: Cliente/Recover/5
        [HttpPost]
        public ActionResult Recover(long id, ClienteViewModel objeto)
        {
            try
            {
                
                sv.Recover(id);
                ClienteModel c = sv.Find(id);

                TempData["Nome"] = c.Nome;
                TempData["Acao"] = "ativado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View();
            }
        }
    }
}

GoltaraSoft.SpaWeb.Web/Controllers/ProdutoController.cs
using AutoMapper;
using GoltaraSolutions.SpaWeb.Web.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using GoltaraSolutions.Common.Extensions;
using GoltaraSolutions.SpaWeb.Domain.ProdutoContext;
using GoltaraSoft.SysBeauty.Web.Controllers;
using GoltaraSolutions.SpaWeb.Domain.EmpresaContext;

namespace GoltaraSolutions.SpaWeb.Web.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class ProdutoController : BaseController
    {
        private ProdutoDomainServices sv;
        private IMapper _mapp;
        public ProdutoController(ProdutoDomainServices produtoDomainServices)
        {
            sv = produtoDomainServices;

            MapperConfiguration config = new MapperConfiguration(cfg =>
           {
               cfg.CreateMap<ProdutoViewModel, ProdutoModel>();
               cfg.CreateMap<ProdutoModel, ProdutoViewModel>()
                .ForMember(dest => dest.Ativo, opt => opt.MapFrom(src => (!src.Deletado).ToCustomString()));
           });

            _mapp = config.CreateMapper();
        }
        // GET: Produto
        public ActionResult Index(string tipo)
        {
            List<ProdutoModel> listModel = sv.List(UsuarioLogado.IdEmpresa).ToList();
            List<ProdutoViewModel> listView = new List<ProdutoViewModel>();

            switch (tipo)
            {
                case "Ativos":
                    listModel = listModel.Where(i => i.Deletado == false).ToList();
                    ViewBag.Filtro = "Ativos";

                    break;
                case "Inativos":
                    listModel = listModel.Where(i => i.Deletado == true).ToList();
                    ViewBag.Filtro = "Inativos";

                    break;
                case "Todos":
                    listModel = listModel.ToList();
                    ViewBag.Filtro = "Todos";

                    break;
                default:
                    listModel = listModel.Where(i => i.Deletado == false).ToList();
                    ViewBag.Filtro = "Ativos";

                    break;
            }

            listModel.ForEach(x => listView.Add(_mapp.Map<ProdutoViewModel>(x)));

            return View(listView);
        }

        // GET: Produto/Details/5
        public ActionResult Details(long id)
        {
            ProdutoModel Produto = sv.Find(id);

            return View(_mapp.Map<ProdutoViewModel>(Produto));
        }

        // GET: Produto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Produto/Create
        [HttpPost]
        public ActionResult Create(ProdutoViewModel objeto)
        {
            try
            {

                sv.Cadastrar(UsuarioLogado.IdEmpresa, objeto.Nome, objeto.Preco);

                TempData["Nome"] = objeto.Nome;
                TempData["Acao"] = "criado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View();
            }
        }

        // GET: Produto/Edit/5
        public ActionResult Edit(long id)
        {
            ProdutoModel Produto = sv.Find(id);

            return View(_mapp.Map<ProdutoViewModel>(Produto));
        }

        // POST: Produto/Edit/5
        [HttpPost]
        public ActionResult Edit(long id, ProdutoViewModel objeto)
        {
            try
            {
                sv.Editar(id, objeto.Nome, objeto.Preco);

                TempData["Nome"] = objeto.Nome;
                TempData["Acao"] = "criado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Edit(id);
            }
        }

        // GET: Produto/Delete/5
        public ActionResult Delete(long id)
        {
            ProdutoModel Produto = sv.Find(id);

            return View(_mapp.Map<ProdutoViewModel>(Produto));
        }

        // POST: Produto/Delete/5
        [HttpPost]
        public ActionResult Delete(long id, ProdutoViewModel objeto)
        {
            try
            {

                sv.Delete(id);

                ProdutoModel p = sv.Find(id);
                TempData["Nome"] = p.Nome;
                TempData["Acao"] = "desativado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View();
            }
        }

        // GET: Produto/Recover/5
        public ActionResult Recover(long id)
        {
            ProdutoModel Produto = sv.Find(id);

            return View(_mapp.Map<ProdutoViewModel>(Produto));
        }

        // POST: Produto/Recover/5
        [HttpPost]
        public ActionResult Recover(long id, ProdutoViewModel objeto)
        {
            try
            {

                sv.Recover(id);

                ProdutoModel p = sv.Find(id);
                TempData["Nome"] = p.Nome;
                TempData["Acao"] = "ativado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View();
            }
        }
    }
}

GoltaraSoft.SpaWeb.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using GoltaraSolutions.Common.Identity.ExtensionMethod

<!DOCTYPE html>
<html style="height: auto; min-height: 100%;">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
    <title>@ViewBag.Title - SpaWeb</title>

    @*CSS*@
    @*@Styles.Render("~/Content/adminLTE-css")*@
    @Styles.Render("~/Content/fontawesome-css")
    @Styles.Render("~/Content/simplexTheme-css")
    @Styles.Render("~/Content/select2-css")
    @Styles.Render("~/Content/datepicker-css")
</head>
<body class="layout-top-nav skin-red" style="height: auto; min-height: 100%;">
    <div class="wrapper" style="height: auto; min-height: 100%;">
        <header class="main-header">
            <nav class="navbar-inverse navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        @Html.ActionLink("SpaWeb", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
                        <ul class="nav navbar-nav navbar-left">
                            @if (Request.IsAuthenticated)
                        {
                            <li>
                                <a href="@Url.Action("AlterarSenha", "Account")" class="text-center">
                                    <i class="fa fa-user-o">
                                    </i>
                                    @User.Identity.GetName()
                                </a>
                            </li>
                    }
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="@Url.Action("Index","Home")">
                                    <i class="fa fa-line-chart"></i>
                                    Dashboard
                                </a>
                            </li>
                            @*<li>
                                <a href="@Url.Action("Agenda","Atendimento")">
                                    <i class="fa fa-calendar"></i>
                                    Agenda
                                </a>
                            </li>*@
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    <i class="fa fa-calendar-o"></i>
                                    Agenda
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="@Url.Action("Agenda","Atendimento")">
                                            <i class="fa fa-calendar-o"></i>
                                            Agenda
                                        </a>
                                    </li>
                                    @if (User.IsInRole("Administrador"))
                                {
                                    <li>
                                        <a href="@Url.Action("Index", "Atendimento")">
                                            <i class="fa fa-list"></i>
                                            Atendimentos
                                        </a>
                                    </li>
                            }
                                </ul>
                            </li>
                            @*<li>
                                <a href="@Url.Action("Index","Venda",new { @tipo = "Ativos" })">
                                    <i class="fa fa-shopping-cart"></i>
                                    Vendas
                                </a>
                            </li>*@
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    <i class="fa fa-users"></i>
                                    Clientes
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="@Url.Action("Index","Cliente",new { @tipo = "Ativos" })">
                                            <i class="fa fa-users"></i>
                                            Clientes
                                        </a>
                                    </li>
                                    @if (User.IsInRole("Administrador"))
                                {
                                    <li>
                                        <a href="@Url.Action("Index", "Canal", new { @tipo = "Ativos" })">
                                            <i class="fa fa-external-link"></i>
                                            Origens
                                        </a>
                                    </li>
                            }
                                </ul>
                            </li>
                            @if (User.IsInRole("Administrador"))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    <i class="fa fa-cogs"></i>
                                    Gerenciar
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="@Url.Action("Index","Funcionario",new { @tipo = "Ativos" })">
                                            <i class="fa fa-address-card"></i>
                                            Funcionários
                                        </a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","Servico",new { @tipo = "Ativos" })">
                                            <i class="fa fa-cubes"></i>
                                            Serviços
                                        </a>
                                    </li>
                                    @*<li>
                                        <a href="@Url.Action("Index","Produto",new { @tipo = "Ativos" })">
                                            <i class="fa fa-shopping-bag"></i>
                                            Produtos
                                        </a>
                                    </li>*@
                                    <li class="divider"></li>
                                    <li>
                                        <a href="@Url.Action("Index","Account",new { @tipo = "Ativos" })">
                                            <i class="fa fa-user-o"></i>
                                            Usuários
                                        </a>
                                    </li>
                                </ul>
                            </li>
                    }
                            @if (Request.IsAuthenticated)
                        {
                            <li>
                                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "nav navbar-nav" }))
                            {@Html.AntiForgeryToken()}
                                <a href="javascript:document.getElementById('logoutForm').submit()">
                                    <i class="fa fa-sign-out"></i>
                                    Sair
                                </a>
                            </li>
                    }
                    else
                    {
                        <li>
                            <a href="@Url.Action("Index","Account")" id="loginLink">
                                <i class="fa fa-user-o"></i>
                                Usuários
                            </a>
                        </li>
                }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <div class="content-wrapper" style="min-height:100%;">
            <div class="container well white">
                @RenderBody()
            </div>
        </div>

        <footer class="main-footer">
            <div class="container">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 1.0
                </div>
                <i class="fa fa-copyright" aria-hidden="true"></i> Goltara Solutions - @DateTime.Now.Year | Todos os direitos reservados.
            </div>
            <!-- /.container -->
        </footer>
    </div>

    @*JavaScripts*@
    @Scripts.Render("~/bundles/jquery-js")
    @Scripts.Render("~/bundles/modernizr-js")
    @Scripts.Render("~/bundles/bootstrap-js")
    @Scripts.Render("~/bundles/popover-js")
    @Scripts.Render("~/bundles/tooltip-js")
    @Scripts.Render("~/bundles/chosen-js")
    @Scripts.Render("~/bundles/datepicker-js")

    @RenderSection("scripts", required: false)
</body>
</html>

GoltaraSoft.SpaWeb.Web/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />

    <title>@ViewBag.Title - SpaWeb</title>
    @*CSS*@
    @Styles.Render("~/Content/bootstrap-css")
    @Styles.Render("~/Content/fontawesome-css")
    @Styles.Render("~/Content/datepicker-css")
    @Styles.Render("~/Content/login-css")
    @Styles.Render("~/Content/icheck-css")
    @Styles.Render("~/Content/adminLTE-css")
</head>
<body class="hold-transition login-page">
    @RenderBody()

    @*JavaScripts*@
    @Scripts.Render("~/bundles/jquery-js")
    @Scripts.Render("~/bundles/jquerymask-js")
    @Scripts.Render("~/bundles/bootstrap-js")
    @Scripts.Render("~/bundles/popover-js")
    @Scripts.Render("~/bundles/tooltip-js")
    @Scripts.Render("~/bundles/datepicker-js")
    @Scripts.Render("~/bundles/icheck-js")

    @RenderSection("scripts", required: false)

    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>
</body>
</html>