GoltaraSoft.SpaWeb.Web/Models/AtendimentoViewModel.cs
using GoltaraSolutions.SpaWeb.Domain.ClienteContext;
using GoltaraSolutions.SpaWeb.Domain.FuncionarioContext;
using GoltaraSolutions.SpaWeb.Domain.ServicoContext;
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace GoltaraSolutions.SpaWeb.Web.Models
{
    public class AtendimentoViewModel
    {
        public AtendimentoViewModel()
        {
            DataHora = DateTime.Now;
        }
        public long Id { get; set; }
        public long IdCliente { get; set; }
        [Display(Name = "Cliente")]
        public SelectList Clientes { get; set; }
        public long IdServico { get; set; }
        [Display(Name = "Serviço")]
        public SelectList Servicos { get; set; }
        public long IdFuncionario { get; set; }
        [Display(Name = "Funcionário")]
        public SelectList Funcionarios { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true,
            DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
        [DataType(DataType.Text, ErrorMessage = "A {0} tem que ser uma data.")]
        [Display(Name = "Data/Hora")]
        public DateTime DataHora { get; set; }
        [Display(Name = "Valor")]
        public decimal Valor { get; set; }
        public bool Cancelado { get; set; }
        public bool Concluido { get; set; }
        [Display(Name = "Cliente")]
        public ClienteModel Cliente { get; set; }
        [Display(Name = "Serviço")]
        public ServicoModel Servico { get; set; }
        [Display(Name = "Funcionário")]
        public FuncionarioModel Funcionario { get; set; }

        [Display(Name = "Usuário Agendou")]
        public string UsuarioAgendou { get;  set; }
    }
}

GoltaraSoft.SpaWeb.Web/Controllers/AtendimentoController.cs
using AutoMapper;
using GoltaraSolutions.Common.Extensions;
using GoltaraSolutions.SpaWeb.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using GoltaraSolutions.Common.Identity.ExtensionMethod;
using GoltaraSolutions.SpaWeb.Domain.ClienteContext;
using GoltaraSolutions.SpaWeb.Domain.AgendaContext.Atendimento;
using GoltaraSolutions.SpaWeb.Domain.ServicoContext;
using GoltaraSolutions.SpaWeb.Domain.ClienteContext;
using GoltaraSolutions.SpaWeb.Domain.FuncionarioContext;
using GoltaraSoft.SysBeauty.Web.Controllers;
using GoltaraSolutions.SpaWeb.Domain.EmpresaContext;
using GoltaraSolutions.SpaWeb.Domain.AgendaContext.Atendimento.ReportViews;
using GoltaraSolutions.Common.Domain.Report;

namespace GoltaraSolutions.SpaWeb.Web.Controllers
{
    [Authorize()]
    public class AtendimentoController : BaseController
    {
        private AtendimentoDomainServices sv;
        private ServicoDomainServices svServico;
        private OrigemDomainServices svOrigem;
        private FuncionarioDomainServices svFuncionario;
        private ClienteDomainServices svCliente;
        private IMapper _mapp;

        public AtendimentoController(AtendimentoDomainServices atendimentoDomainServices,
            FuncionarioDomainServices funcionarioDomainServices,
            ServicoDomainServices servicoDomainServices,
            OrigemDomainServices origemDomainServices,
            ClienteDomainServices clienteDomainServices)
        {
            sv = atendimentoDomainServices;
            svCliente = clienteDomainServices;
            svServico = servicoDomainServices;
            svFuncionario = funcionarioDomainServices;
            svOrigem = origemDomainServices;

            MapperConfiguration config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<AtendimentoViewModel, AtendimentoModel>();
                cfg.CreateMap<AtendimentoModel, AtendimentoViewModel>();

                cfg.CreateMap<AtendimentoViewModel, AtendimentoReportView>();
                cfg.CreateMap<AtendimentoReportView, AtendimentoViewModel>();

                cfg.CreateMap<AtendimentoModel, AtendimentoReportView>();
                cfg.CreateMap<AtendimentoReportView, AtendimentoModel>();

                cfg.CreateMap<List<AtendimentoModel>, List<AtendimentoViewModel>>();

                cfg.CreateMap<FiltrosReportView, ListItem>()
                    .ForMember(dest => dest.Value, opt =>
                        opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.Display, opt =>
                        opt.MapFrom(src => src.Nome));

                cfg.CreateMap<ClienteModel, ListItem>()
                    .ForMember(dest => dest.Value, opt =>
                        opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.Display, opt =>
                        opt.MapFrom(src => src.Nome));
                cfg.CreateMap<ServicoModel, ListItem>()
                    .ForMember(dest => dest.Value, opt =>
                        opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.Display, opt =>
                        opt.MapFrom(src => src.Nome));
                cfg.CreateMap<FuncionarioModel, ListItem>()
                    .ForMember(dest => dest.Value, opt =>
                        opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.Display, opt =>
                        opt.MapFrom(src => src.Nome));
                cfg.CreateMap<OrigemModel, ListItem>()
                    .ForMember(dest => dest.Value, opt =>
                        opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.Display, opt =>
                        opt.MapFrom(src => src.Nome));
            });

            _mapp = config.CreateMapper();
        }

        public ActionResult Index(AtendimentoReportViewModel report)
        {

            if (report == null)
            {
                report = new AtendimentoReportViewModel();
            }


            if (report.Clientes == null)
            {
                List<FiltrosReportView> clientes = svCliente.ListarFiltro(UsuarioLogado.IdEmpresa).ToList();
                List<ListItem> itens = _mapp.Map<List<ListItem>>(clientes);
                itens.Insert(0, new ListItem("Selecione...", null));

                report.Clientes = new SelectList(itens, "Value", "Display");
            }

            if (report.Servicos == null)
            {
                List<FiltrosReportView> Servicos = svServico.ListarFiltros(UsuarioLogado.IdEmpresa).ToList();
                List<ListItem> itens = _mapp.Map<List<ListItem>>(Servicos);
                itens.Insert(0, new ListItem("Selecione...", null));

                report.Servicos = new SelectList(itens, "Value", "Display");
            }

            if (report.Funcionarios == null)
            {
                List<FiltrosReportView> Funcionarios = svFuncionario.ListarFiltros(UsuarioLogado.IdEmpresa).ToList();
                List<ListItem> itens = _mapp.Map<List<ListItem>>(Funcionarios);
                itens.Insert(0, new ListItem("Selecione...", null));

                report.Funcionarios = new SelectList(itens, "Value", "Display");
            }

            if (report.Origens == null)
            {
                List<FiltrosReportView> origens = svOrigem.ListarFiltro(UsuarioLogado.IdEmpresa).ToList();
                List<ListItem> itens = _mapp.Map<List<ListItem>>(origens);
                itens.Insert(0, new ListItem("Selecione...", null));

                report.Origens = new SelectList(itens, "Value", "Display");
            }


            //if (report.Status == null)
            //{
            //    List<ListItem> itens = new List<ListItem>();
            //    itens.Insert(0, new ListItem("Selecione...", null));
            //    itens.Insert(1, new ListItem("Abertos", null));
            //    itens.Insert(2, new ListItem("Cancelados", null));
            //    itens.Insert(3, new ListItem("Concluidos", null));

            //    report.Status = new SelectList(itens, "Value", "Display");
            //    report.iStatus = 0;
            //}

            switch (report.Status)
            {
                case Status.Aberto:
                    report.Cancelado = false;
                    report.Concluido = false;
                    break;
                case Status.Cancelado:
                    report.Cancelado = true;
                    break;
                case Status.Concluído:
                    report.Concluido = true;
                    break;
                case Status.Todos:
                    report.Cancelado = null;
                    report.Concluido = null;
                    break;
                default:
                    break;
            }

            List<AtendimentoReportView> atendimentos = sv.Relatorio(UsuarioLogado.IdEmpresa, report.DataHoraInicial.FirstHourOfDay(), report.DataHoraFinal.LastHourOfDay(),
                report.IdCliente, report.IdServico, report.IdFuncionario, report.IdOrigem,
                report.Cancelado, report.Concluido);

            //List<AtendimentoViewModel> listView = new List<AtendimentoViewModel>();
            //if (atendimentos.IsNotNull())
            //{
            //    atendimentos.ForEach(o => listView.Add(_mapp.Map<AtendimentoViewModel>(o)));
            //}

            report.Atendimentos = atendimentos;

            return View(report);
        }

        public ActionResult PorCliente(AtendimentoReportAgrupadoViewModel report)
        {

            if (report == null)
            {
                report = new AtendimentoReportAgrupadoViewModel();
            }

            if (report.Clientes == null)
            {
                List<FiltrosReportView> clientes = svCliente.ListarFiltro(UsuarioLogado.IdEmpresa).ToList();
                List<ListItem> itens = _mapp.Map<List<ListItem>>(clientes);
                itens.Insert(0, new ListItem("Selecione...", null));

                report.Clientes = new SelectList(itens, "Value", "Display");
            }

            if (report.Servicos == null)
            {
                List<FiltrosReportView> Servicos = svServico.ListarFiltros(UsuarioLogado.IdEmpresa).ToList();
                List<ListItem> itens = _mapp.Map<List<ListItem>>(Servicos);
                itens.Insert(0, new ListItem("Selecione...", null));

                report.Servicos = new SelectList(itens, "Value", "Display");
            }

            if (report.Funcionarios == null)
            {
                List<FiltrosReportView> Funcionarios = svFuncionario.ListarFiltros(UsuarioLogado.IdEmpresa).ToList();
                List<ListItem> itens = _mapp.Map<List<ListItem>>(Funcionarios);
                itens.Insert(0, new ListItem("Selecione...", null));

                report.Funcionarios = new SelectList(itens, "Value", "Display");
            }

            if (report.Origens == null)
            {
                List<FiltrosReportView> origens = svOrigem.ListarFiltro(UsuarioLogado.IdEmpresa).ToList();
                List<ListItem> itens = _mapp.Map<List<ListItem>>(origens);
                itens.Insert(0, new ListItem("Selecione...", null));

                report.Origens = new SelectList(itens, "Value", "Display");
            }

            switch (report.Status)
            {
                case Status.Aberto:
                    report.Cancelado = false;
                    report.Concluido = false;
                    break;
                case Status.Cancelado:
                    report.Cancelado = true;
                    break;
                case Status.Concluído:
                    report.Concluido = true;
                    break;
                case Status.Todos:
                    report.Cancelado = null;
                    report.Concluido = null;
                    break;
                default:

GoltaraSoft.SpaWeb.Web/Views/Atendimento/Agenda.cshtml
@{
    ViewBag.Title = "Agenda";
}
@Styles.Render("~/Content/fullcalendar-css")
@Styles.RenderFormat(BundlesFormats.PRINT, "~/Content/fullcalendar-print-css")

<section class="content-header">
    <h1 class="box-title">
        @ViewBag.Title
        <small>Sua agenda de atendimentos a serem prestados.</small>
        <span>
            <a href="@Url.Action("Create")" class="btn btn-primary btn-sm pull-right">
                <i class="fa fa-plus" aria-hidden="true"></i>
                Agendar
            </a>
        </span>
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default">
                <div class="box-body">
                    @if (TempData["Acao"] != null && !string.IsNullOrWhiteSpace(TempData["Acao"].ToString()))
                    {
                        <div class="alert alert-dismissible alert-success">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            Muito bem! <strong>@TempData["Nome"].ToString()</strong> foi @TempData["Acao"].ToString() com sucesso.
                        </div>
                    }

                    <div id='calendar' class="fc fc-unthemed fc-ltr"></div>
                </div>
            </div>
        </div>
    </div>
</section>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><span id="eventTitle"></span></h4>
            </div>
            <div class="modal-body">
                <div id="pDetails"></div>
            </div>
            <div id="pFooter" class="modal-footer"></div>
        </div>
    </div>
</div>

@section scripts {
    @Scripts.Render("~/bundles/moment-js")
    @Scripts.Render("~/bundles/fullcalendar-js")

    <script>
    $(document).ready(function () {
        var events = [];
        $.ajax({
            type: "GET",
            url: "@Url.Action("GetEvents", "Atendimento")",
            success: function (data) {
                $.each(data, function (i, v) {
                    events.push({
                        title: v.Servico + ' - ' + v.Cliente,
                        funcionario: v.Funcionario,
                        Cliente: v.Cliente,
                        Servico: v.Servico,
                        Status: v.Status.toString(),
                        Id: v.Id.toString(),
                        start: moment(v.DataHoraString).toDate(),
                        end: v.DataHoraEncerramentoString != null ? moment(v.DataHoraEncerramentoString) : null,
                        allDay: false,
                        color: '#3c8dbc'
                    });
                })

                GenerateCalender(events);
            },
            error: function (error) {
                alert(error);
            }
        })

        function GenerateCalender(events) {
            $('#calendar').fullCalendar('destroy');
            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'agendaDay, agendaWeek, listWeek'
                },
                visibleRange: {
                    start: @DateTime.Now.AddMonths(-3).ToString("yyyy-MM-dd"),
                    end: @DateTime.Now.AddMonths(3).ToString("yyyy-MM-dd")
                },
                locale: 'pt-br',
                defaultDate: new Date(),
                navLinks: true, // can click day/week names to navigate views
                editable: false,
                eventLimit: true, // allow "more" link when too many events
                minTime: '08:00:00',
                maxTime: '22:00:00',
                contentHeight: 638,
                allDaySlot: false,
                defaultView: 'agendaWeek',
                events: events,
                eventClick: function (calEvent, jsEvent, view) {
                    $('#myModal #eventTitle').text(calEvent.title);
                    var $description = $('<span/>');
                    //if (calEvent.end != null) {
                    //    $description.append($('<p/>').html('<b>End:</b>' + calEvent.end.format("DD-MMM-YYYY HH:mm a")));
                    //}

                    $description.append($('<div class="form-group" />').html('<label class="label-detail">Cliente: </label> ' + calEvent.Cliente));
                    $description.append($('<div class="form-group" />').html('<label class="label-detail">Serviço: </label> ' + calEvent.Servico));
                    $description.append($('<div class="form-group" />').html('<label class="label-detail">Funcionário: </label> ' + calEvent.funcionario));
                    $description.append($('<div class="form-group" />').html('<label class="label-detail">Horário: </label> ' + calEvent.start.format("DD/MM/YYYY HH:mm")));
                    $description.append($('<div class="form-group" />').html('<label class="label-detail">Status: </label> ' + calEvent.Status));
                    $('#myModal #pDetails').empty().html($description);

                    var $footer = '<button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>';
                    $footer = $footer + '<a href="/Atendimento/Details/0' + calEvent.Id + '" class="btn btn-primary pull-right">Detalhes</a>';
                    $('#myModal #pFooter').empty().html($footer);



                    $('#myModal').modal();
                }
            })
        }
    })
    </script>
}

GoltaraSoft.SpaWeb.Web/Views/Atendimento/Create.cshtml
@model GoltaraSolutions.SpaWeb.Web.Models.AtendimentoViewModel
@{
    ViewBag.Title = "Agendar Atendimento";
    if (Model != null)
    {
        Model.DataHora = DateTime.Now;
    }
}
@Styles.Render("~/Content/datetimepicker-css")

<section class="content-header">
    <h1 class="box-title">
        @ViewBag.Title
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-default">
                @using (Html.BeginForm())
                {
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-12">
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary("", new { @class = "alert-danger", @role = "alert" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6 col-lg-6 col-xs-12">
                                @Html.LabelFor(model => model.Clientes, htmlAttributes: new { @class = "label-action" })
                                @Html.DropDownListFor(model => model.IdCliente, (SelectList)Model.Clientes, new { @class = "select2 form-control", data_placeholder = "Pesquise...", data_toggle = "tooltip", data_placement = "bottom", title = "Selecione o Cliente que será atendido" })
                            </div>
                            <div class="form-group col-md-6 col-lg-6 col-xs-12">
                                <label class="label-action">
                                    Serviço
                                    <i class="fa fa-info-circle " aria-hidden="true"
                                       data-toggle="tooltip" data-placement="right"
                                       data-container="body" title="Serviços que não possuem preço fixo podem ter seu preço alterado no momento de conclusão do atendimento."></i>
                                </label>
                                @Html.DropDownListFor(model => model.IdServico, (SelectList)Model.Servicos, new { @class = "select2 form-control", data_placeholder = "Pesquise...", data_toggle = "tooltip", data_placement = "bottom", title = "Selecione o Serviço que o Cliente deseja" })
                            </div>
                            <div class="form-group col-md-6 col-lg-6 col-xs-12">
                                @Html.LabelFor(model => model.Funcionarios, htmlAttributes: new { @class = "label-action" })
                                @Html.DropDownListFor(model => model.IdFuncionario, (SelectList)Model.Funcionarios, new { @class = "select2 form-control", data_placeholder = "Pesquise...", data_toggle = "tooltip", data_placement = "bottom", title = "Selecione o Funcionário que vai realizar o Serviço" })
                            </div>
                            <div class="form-group col-md-6 col-lg-6 col-xs-12">
                                @Html.LabelFor(model => model.DataHora, htmlAttributes: new { @class = "label-action" })
                                @Html.EditorFor(model => model.DataHora, new { htmlAttributes = new { @class = "datetimepicker form-control" } })
                                @Html.ValidationMessageFor(model => model.DataHora, "", new { @for = "inputError", @class = "text-danger", @value = "01/01/1980", data_toggle = "tooltip", data_placement = "bottom", title = "Selecione a Data e Hora que o Serviço será realizado" })
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="row">
                            <div class="col-md-12">
                                <a href="@Url.Action("Index")" class="btn btn-default btn-sm"><i class="fa fa-arrow-left"></i> Voltar</a>
                                <button type="submit" class="btn btn-primary btn-sm pull-right"><i class="fa fa-save"></i> Salvar</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

@section scripts {
    @Scripts.Render("~/bundles/moment-js")
    @Scripts.Render("~/bundles/datetimepicker-js")

    <script type="text/javascript">
        $(function () {
            $('.datetimepicker').datetimepicker({
                locale: 'pt-br'
            });
        });
    </script>
}

GoltaraSoft.SpaWeb.Web/Views/Atendimento/Details.cshtml
@model GoltaraSolutions.SpaWeb.Web.Models.AtendimentoViewModel
@{
    ViewBag.Title = Model.DataHora.ToString("dd/MM/yyyy HH:mm") + " - " + Model.Cliente.Nome;
}
<section class="content-header">
    <h1 class="box-title">
        @ViewBag.Title
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-default">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Cliente, new { @class = "label-detail" })
                                @Html.DisplayFor(m => m.Cliente.Nome)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Funcionario, new { @class = "label-detail" })
                                @Html.DisplayFor(m => m.Funcionario.Nome)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Valor, new { @class = "label-detail" })
                                @Html.DisplayFor(m => m.Valor)
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Servico, new { @class = "label-detail" })
                                @Html.DisplayFor(m => m.Servico.Nome)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.DataHora, new { @class = "label-detail" })
                                @Html.DisplayFor(m => m.DataHora)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.UsuarioAgendou, new { @class = "label-detail" })
                                @Html.DisplayFor(m => m.UsuarioAgendou)
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <a href="@Url.Action("Index")" class="btn btn-default btn-sm pull-left"><i class="fa fa-arrow-left"></i> Voltar</a>
                                <span class="pull-right">
                                    @{ if (Model.Concluido != true && Model.Cancelado != true)
                                        {
                                            <a href="#" data-toggle="modal" data-target="#modalConcluir" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Concluir</a>
                                            <a href="@Url.Action("Edit","Atendimento", new { @id = Model.Id } )" class="btn btn-danger btn-sm"><i class="fa fa-edit"></i> Editar</a>
                                            <a href="#" data-toggle="modal" data-target="#modalCancel" class="btn btn-primary btn-sm"><i class="fa fa-trash"></i> Cancelar</a>
                                        }
                                    }
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Modal de Desativação -->
<div class="modal fade" id="modalCancel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Cancelar Atendimento</h4>
            </div>
            @using (Html.BeginForm("Cancel", "Atendimento", new { @id = Model.Id }, FormMethod.Post, new { @class = "form-horizontal", @role = "form" }))
            {
                <div class="modal-body">
                    <div class="form-group">
                        <div class="col-md-12">
                            <label class="alert alert-dismissible alert-warning">
                                <b>Atenção!</b> Quando um atendimento é cancelado, ele não poderá mais ser editado.
                            </label>

                            <p>Você tem certeza que deseja <b>cancelar</b> este atendimento ?</p>

                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary pull-right">Confirmar</button>
                </div>
            }
        </div>
    </div>
</div>

<!-- Modal de Ativa -->
<div class="modal fade" id="modalConcluir" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Concluir Atendimento</h4>
            </div>
            @using (Html.BeginForm("Concluir", "Atendimento", new { @id = Model.Id }, FormMethod.Post, new { @role = "form" }))
            {
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="alert alert-dismissible alert-warning">
                                    <b>Atenção!</b> Quando um atendimento é concluido, ele não poderá mais ser editado.
                                </label>
                                <p>Você tem certeza que deseja <b>concluir</b> este atendimento ?</p>
                            </div>

                            <div class="form-group">
                                @if (Model.Servico.PrecoFixo != true)
                                {
                                    @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "label-action" })
                                    @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control money2", data_toggle = "tooltip", data_placement = "bottom", title = "Valor final do Atendimento" } })
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary pull-right">Confirmar</button>
                </div>
            }
        </div>
    </div>
</div>