GoltaraSoft.SpaWeb.Web/Models/FuncionarioViewModel.cs
namespace GoltaraSolutions.SpaWeb.Web.Models
{
    public sealed class FuncionarioViewModel : FuncionarioEditViewModel
    {
        public FuncionarioViewModel() : base()
        {
        }
    }
}

GoltaraSoft.SpaWeb.Web/Controllers/FuncionarioController.cs
using AutoMapper;
using GoltaraSolutions.SpaWeb.Web.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using GoltaraSolutions.Common.Extensions;
using GoltaraSolutions.SpaWeb.Domain.ServicoContext;
using GoltaraSolutions.SpaWeb.Domain.FuncionarioContext;
using GoltaraSoft.SysBeauty.Web.Controllers;
using GoltaraSolutions.SpaWeb.Domain.EmpresaContext;
using GoltaraSolutions.Common.Domain.Report;

namespace GoltaraSolutions.SpaWeb.Web.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class FuncionarioController : BaseController
    {
        private FuncionarioDomainServices sv;
        private ServicoDomainServices svServico;
        private IMapper _mapp;
        public FuncionarioController(FuncionarioDomainServices funcionarioDomainServices,
            ServicoDomainServices servicoDomainServices)
        {
            sv = funcionarioDomainServices;
            svServico = servicoDomainServices;

            MapperConfiguration config = new MapperConfiguration(cfg =>
           {
               cfg.CreateMap<FuncionarioViewModel, FuncionarioModel>();

               cfg.CreateMap<FuncionarioModel, FuncionarioViewModel>()
                .ForMember(dest => dest.Ativo, opt => opt.MapFrom(src => (!src.Deletado).ToCustomString()))
                .ForMember(dest => dest.ServicosSelecionados, opt => opt.Ignore())
                .ForMember(dest => dest.ServicosPossiveis, opt => opt.Ignore())
                .ForMember(dest => dest.ServicosPrestados, opt => opt.Ignore()); ;
           });

            _mapp = config.CreateMapper();
        }
        // GET: Funcionario
        public ActionResult Index(string tipo)
        {
            List<FuncionarioModel> listModel = sv.List(UsuarioLogado.IdEmpresa).ToList();
            List<FuncionarioViewModel> listView = new List<FuncionarioViewModel>();

            switch (tipo)
            {
                case "Ativos":
                    listModel = listModel.Where(i => i.Deletado == false).ToList();
                    ViewBag.Filtro = "Ativos";

                    break;
                case "Inativos":
                    listModel = listModel.Where(i => i.Deletado == true).ToList();
                    ViewBag.Filtro = "Inativos";

                    break;
                case "Todos":
                    listModel = listModel.ToList();
                    ViewBag.Filtro = "Todos";

                    break;
                default:
                    listModel = listModel.Where(i => i.Deletado == false).ToList();
                    ViewBag.Filtro = "Ativos";

                    break;
            }

            listModel.ForEach(x =>
            {
                FuncionarioViewModel funcView = _mapp.Map<FuncionarioViewModel>(x);
                listView.Add(funcView);
            }
            );

            return View(listView);
        }

        // GET: Funcionario/Details/5
        public ActionResult Details(long id)
        {
            FuncionarioModel Funcionario = sv.Find(id);
            FuncionarioViewModel funcionarioView = _mapp.Map<FuncionarioViewModel>(Funcionario);

            List<FiltrosReportView> servicos = svServico.ListarFiltros(UsuarioLogado.IdEmpresa).ToList();

            funcionarioView.ServicosPossiveis = new MultiSelectList(servicos, "Id", "Nome");
            funcionarioView.ServicosSelecionados = Funcionario.Servicos?.Select(s => s.Id).ToArray();

            if (Funcionario.Servicos.IsNotNull())
                Funcionario.Servicos.ToList().ForEach(y =>
                {
                    funcionarioView.ServicosPrestados.Add(y);
                }
                );

            return View(funcionarioView);
        }

        // GET: Funcionario/Create
        public ActionResult Create()
        {
            FuncionarioViewModel Funcionario = new FuncionarioViewModel();

            List<FiltrosReportView> servicos = svServico.ListarFiltros(UsuarioLogado.IdEmpresa).ToList();
            
            Funcionario.ServicosPossiveis = new MultiSelectList(servicos, "Id", "Nome");
            Funcionario.ServicosSelecionados = new long[] { };

            return View(Funcionario);
        }

        // POST: Funcionario/Create
        [HttpPost]
        public ActionResult Create(FuncionarioViewModel objeto)
        {
            try
            {


                sv.Cadastrar(UsuarioLogado.IdEmpresa,
                    objeto.Nome,
                    objeto.DataNascimento,
                    objeto.Telefone,
                    objeto.Celular,
                    objeto.Email,
                    objeto.Sexo,
                    objeto.ServicosSelecionados);

                TempData["Nome"] = objeto.Nome;
                TempData["Acao"] = "criado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Create();
            }
        }

        // GET: Funcionario/Edit/5
        public ActionResult Edit(long id)
        {
            FuncionarioModel Funcionario = sv.Find(id);
            FuncionarioViewModel funcionarioView = _mapp.Map<FuncionarioViewModel>(Funcionario);

            List<FiltrosReportView> servicos = svServico.ListarFiltros(UsuarioLogado.IdEmpresa).ToList();

            funcionarioView.ServicosPossiveis = new MultiSelectList(servicos, "Id", "Nome");
            funcionarioView.ServicosSelecionados = Funcionario.Servicos?.Select(s => s.Id).ToArray();

            return View(funcionarioView);
        }

        // POST: Funcionario/Edit/5
        [HttpPost]
        public ActionResult Edit(long id, FuncionarioEditViewModel objeto)
        {
            try
            {


                sv.Editar(objeto.Id, objeto.Nome, objeto.DataNascimento, objeto.Telefone, objeto.Celular, objeto.Email, objeto.Sexo, objeto.ServicosSelecionados);

                TempData["Nome"] = objeto.Nome;
                TempData["Acao"] = "editado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);


                FuncionarioModel Funcionario = sv.Find(id);
                FuncionarioViewModel funcionarioView = _mapp.Map<FuncionarioViewModel>(Funcionario);

                List<FiltrosReportView> servicos = svServico.ListarFiltros(UsuarioLogado.IdEmpresa).ToList();
   
                funcionarioView.ServicosPossiveis = new MultiSelectList(servicos, "Id", "Nome");
                funcionarioView.ServicosSelecionados = Funcionario.Servicos?.Select(s => s.Id).ToArray();

                return View(funcionarioView);
            }
        }

        // GET: Funcionario/Delete/5
        public ActionResult Delete(long id)
        {
            FuncionarioModel Funcionario = sv.Find(id);

            return View(_mapp.Map<FuncionarioViewModel>(Funcionario));
        }

        // POST: Funcionario/Delete/5
        [HttpPost]
        public ActionResult Delete(long id, FuncionarioViewModel objeto)
        {
            try
            {

                sv.Delete(id);

                FuncionarioModel f = sv.Find(id);
                TempData["Nome"] = f.Nome;
                TempData["Acao"] = "desativado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View();
            }
        }

        // GET: Funcionario/Recover/5
        public ActionResult Recover(long id)
        {
            FuncionarioModel Funcionario = sv.Find(id);

            return View(_mapp.Map<FuncionarioViewModel>(Funcionario));
        }

        // POST: Funcionario/Recover/5
        [HttpPost]
        public ActionResult Recover(long id, FuncionarioViewModel objeto)
        {
            try
            {

                sv.Recover(id);

                FuncionarioModel f = sv.Find(id);
                TempData["Nome"] = f.Nome;
                TempData["Acao"] = "ativado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View();
            }
        }
    }
}

GoltaraSoft.SpaWeb.Web/Views/Funcionario/Create.cshtml
@model GoltaraSolutions.SpaWeb.Web.Models.FuncionarioViewModel

@{
    ViewBag.Title = "Novo Funcionário";
    Model.DataNascimento = DateTime.Now;
}
<section class="content-header">
    <h1>
        @ViewBag.Title
        @*<small>
                Seus clientes cadastrados. Você deve ter suas origens cadastradas para cadastrar os clientes.
            </small>*@
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-default">
                @using (Html.BeginForm())
                {
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-12">
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary("", new { @class = "alert-danger", @role = "alert" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6 col-lg-6 col-xs-12">
                                @Html.LabelFor(model => model.Nome)
                                @Html.EditorFor(model => model.Nome, new
                               {
                                   htmlAttributes = new
                                   {
                                       @class = "form-control",
                                       data_toggle = "tooltip",
                                       data_placement = "bottom",
                                       title = "Nome do Cliente"
                                   }
                               })
                            </div>
                            <div class="form-group col-md-6 col-lg-6 col-xs-12">
                                @Html.LabelFor(model => model.Sexo)
                                @Html.DropDownListFor(model => model.Sexo, (SelectList)Model.Sexos,
                                        new
                                        {
                                            @id = "select",
                                            @class = "form-control",
                                            @data_toggle = "tooltip",
                                            @data_placement = "bottom",
                                            @title = "Sexo do Cliente"
                                        })
                            </div>
                            <div class="form-group col-md-6 col-lg-6 col-xs-12">
                                @Html.LabelFor(model => model.Celular)

                                @Html.EditorFor(model => model.Celular, new
                               {
                                   htmlAttributes = new
                                   {
                                       @class = "form-control sp_celphones",
                                       @placeholder = "(00) 00000-0000",
                                       data_toggle = "tooltip",
                                       data_placement = "bottom",
                                       title = "Telefone celular do Cliente"
                                   }
                               })
                            </div>
                            <div class="form-group col-md-6 col-lg-6 col-xs-12">
                                @Html.LabelFor(model => model.Telefone)
                                @Html.EditorFor(model => model.Telefone, new
                               {
                                   htmlAttributes = new
                                   {
                                       @class = "form-control phone_with_ddd",
                                       @placeholder = "(00) 0000-0000",
                                       data_toggle = "tooltip",
                                       data_placement = "bottom",
                                       title = "Telefone fixo do Cliente"
                                   }
                               })

                            </div>
                            <div class="form-group col-md-6 col-lg-6 col-xs-12">
                                @Html.LabelFor(model => model.Email)
                                @Html.EditorFor(model => model.Email, new
                               {
                                   htmlAttributes = new
                                   {
                                       @class = "form-control",
                                       placeholder = "seuemail@email.com",
                                       data_toggle = "tooltip",
                                       data_placement = "bottom",
                                       title = "Email do Cliente"
                                   }
                               })
                            </div>
                            <div class="form-group col-md-6 col-lg-6 col-xs-12">

                                @Html.LabelFor(model => model.DataNascimento)
                                @Html.EditorFor(model => model.DataNascimento,
                                        new
                                        {
                                            htmlAttributes = new
                                            {
                                                @class = "datepicker form-control date",
                                                @placeholder = "__/__/____",
                                                data_toggle = "tooltip",
                                                data_placement = "bottom",
                                                title = "Data de nascimento do Cliente"
                                            }
                                        })
                            </div>
                            <div class="form-group col-md-6 col-lg-6 col-xs-12">
                                <label for="select">Serviços</label>
                                @Html.ListBoxFor(model => model.ServicosSelecionados, Model.ServicosPossiveis,
                                           new
                                           {
                                               @class = "form-control select2",
                                               data_toggle = "tooltip",
                                               data_placement = "bottom",
                                               title = "Serviços prestados pelo funcionário.",
                                               @multiple = "multiple"
                                           })
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="row">
                            <div class="col-md-12">
                                <a href="@Url.Action("Index")" class="btn btn-default btn-sm"><i class="fa fa-arrow-left"></i> Voltar</a>
                                <button type="submit" class="btn btn-primary btn-sm pull-right"><i class="fa fa-save"></i> Salvar</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

GoltaraSoft.SpaWeb.Web/Views/Funcionario/Details.cshtml
@model GoltaraSolutions.SpaWeb.Web.Models.FuncionarioViewModel
@{
    ViewBag.Title = Model.Nome;
}
<section class="content-header">
    <h1 class="box-title">
        @Html.Label(Model.Nome)
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-default">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Nome, new { @class = "label-detail" })
                                @Html.DisplayFor(m => m.Nome)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Celular, new { @class = "label-detail" })
                                @Html.DisplayFor(m => m.Celular)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Email, new { @class = "label-detail" })
                                @Html.DisplayFor(m => m.Email)
                            </div>
                            <div class="form-group">
                                <label class="label-detail">
                                    Serviços
                                </label>
                                @foreach (var item in Model.ServicosPrestados)
                                {
                                    <p>
                                        @item.Nome
                                    </p>
                                }
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Sexo, new { @class = "label-detail" })
                                @Html.DisplayFor(m => m.Sexo)
                            </div>
                            <div class="form-group">

                                @Html.LabelFor(m => m.Telefone, new { @class = "label-detail" })
                                @Html.DisplayFor(m => m.Telefone)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.DataNascimento, new { @class = "label-detail" })
                                @Html.DisplayFor(m => m.DataNascimento)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Ativo, new { @class = "label-detail" })
                                @Html.DisplayFor(m => m.Ativo)
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <a href="@Url.Action("Index")" class="btn btn-default btn-sm pull-left"><i class="fa fa-arrow-left"></i> Voltar</a>
                                <span class="pull-right">
                                    @{ if (Model.Ativo == "Sim")
                                        {
                                            <a href="#" data-toggle="modal" data-target="#modalDelete" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Desativar</a>
                                        }
                                    }
                                    @{ if (Model.Ativo == "Sim")
                                        {
                                            <a href="@Url.Action("Edit","Funcionario", new { @id = Model.Id } )" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Editar</a>
                                        }
                                    }
                                    @{ if (Model.Ativo != "Sim")
                                        {
                                            <a href="#" data-toggle="modal" data-target="#modalRecover" class="btn btn-success btn-sm"><i class="fa fa-undo"></i> Ativar</a>
                                        }
                                    }
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Modal de Desativação -->
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Desativar Funcionário</h4>
            </div>
            @using (Html.BeginForm("Delete", "Funcionario", new { @id = Model.Id }, FormMethod.Post, new { @class = "form-horizontal", @role = "form" }))
            {
                <div class="modal-body">
                    <div class="form-group">
                        <div class="col-md-12">
                            <h3>Você tem certeza que deseja <b>desativar</b> o Funcionario <b>@Model.Nome</b> ?</h3>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary pull-right">Confirmar</button>
                </div>
            }
        </div>
    </div>
</div>

<!-- Modal de Ativa -->
<div class="modal fade" id="modalRecover" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Ativar Funcionário</h4>
            </div>
            @using (Html.BeginForm("Recover", "Funcionario", new { @id = Model.Id }, FormMethod.Post, new { @class = "form-horizontal", @role = "form" }))
            {
                <div class="modal-body">
                    <div class="form-group">
                        <div class="col-md-12">
                            <h3>Você tem certeza que deseja <b>ativar</b> o Funcionario <b>@Model.Nome</b> ?</h3>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary pull-right">Confirmar</button>
                </div>
            }
        </div>
    </div>
</div>

GoltaraSoft.SpaWeb.Web/Views/Funcionario/Index.cshtml
@model IEnumerable<GoltaraSolutions.SpaWeb.Web.Models.FuncionarioViewModel>

@{
    ViewBag.Title = "Funcionários";
}
<section class="content-header">
    <h1 class="box-title">
        @ViewBag.Title
        <small>Funcionários que prestam algum serviço na sua empresa. Você deve ter os serviços cadastrados para cadastrar os funcionários.</small>
    </h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default">
                <div class="box-header">
                    @if (TempData["Acao"] != null && !string.IsNullOrWhiteSpace(TempData["Acao"].ToString()))
                    {
                        <div class="alert alert-dismissible alert-success">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            Muito bem! <strong>@TempData["Nome"].ToString()</strong> foi @TempData["Acao"].ToString() com sucesso.
                        </div>
                    }
                    <div class="float-none form-group">
                        <span class="">
                            <a href="@Url.Action("Create")" class="btn btn-default btn-sm">
                                <i class="fa fa-plus" aria-hidden="true"></i>
                                Novo
                            </a>
                        </span>
                        <div class="pull-right">
                            <span class="label-filter">
                                <i class="fa fa-filter" aria-hidden="true"></i>
                                <label>@ViewBag.Filtro</label>
                            </span>
                            <a class="btn btn-default btn-sm" role="button" data-toggle="collapse" href="#collapseFiltros" aria-expanded="false" aria-controls="collapseExample">
                                <i class="fa fa-search"></i>
                                Filtros
                            </a>
                        </div>
                    </div>

                    <div class="collapse" id="collapseFiltros">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    Filtros
                                </h3>
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="btn-group">
                                            @Html.ActionLink("Ativos", "Index", "Funcionario", new { @tipo = "Ativos" }, new { @class = "btn btn-success btn-sm" })
                                            @Html.ActionLink("Inativos", "Index", "Funcionario", new { @tipo = "Inativos" }, new { @class = "btn btn-primary btn-sm" })
                                            @Html.ActionLink("Todos", "Index", "Funcionario", new { @tipo = "Todos" }, new { @class = "btn btn-default btn-sm" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table table-striped table-hover display responsive nowrap" id="dataTable" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Nome)</th>
                                <th>@Html.DisplayNameFor(model => model.Telefone)</th>
                                <th>@Html.DisplayNameFor(model => model.Celular)</th>
                                <th>@Html.DisplayNameFor(model => model.Email)</th>
                                <th>@Html.DisplayNameFor(model => model.Ativo)</th>
                                <th class="text-center col-md-2">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr class="odd gradeX">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Nome)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Telefone)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Celular)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Email)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Ativo)
                                    </td>
                                    <td class="text-center h4">
                                        <div class="row">
                                            <div class="col-md-6 col-xs-6">
                                                <span class="ficon">
                                                    <a href="@Url.Action("Details", "Funcionario", new { id = item.Id })">
                                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                                    </a>
                                                </span>
                                            </div>
                                            <div class="col-md-6 col-xs-6">
                                                @if (!item.Deletado)
                                                {
                                                    <span class="ficon">
                                                        <a href="@Url.Action("Edit", "Funcionario", new { id = item.Id })">
                                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                                        </a>
                                                    </span>
                                                }
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts {
    @Styles.Render("~/Content/datatables-css")
    @Scripts.Render("~/bundles/moment-js")
    @Scripts.Render("~/bundles/datatables-js")
}