GoltaraSoft.SpaWeb.Web/Models/OrigemViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GoltaraSolutions.SpaWeb.Web.Models
{
    public sealed class OrigemViewModel : AggregateViewModel
    {
        public OrigemViewModel()
        {
        }
        
        [MaxLength(15, ErrorMessage = "O {0} deve ter no maximo {1} letras."),
          MinLength(3, ErrorMessage = "O {0} deve ter pelo menos {1} letras.")]
        public string Nome { get; set; }

    }
}

GoltaraSoft.SpaWeb.Web/Controllers/OrigemController.cs
using AutoMapper;
using GoltaraSolutions.SpaWeb.Web.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using GoltaraSolutions.Common.Extensions;
using GoltaraSolutions.SpaWeb.Domain.ClienteContext;
using GoltaraSoft.SysBeauty.Web.Controllers;
using GoltaraSolutions.SpaWeb.Domain.EmpresaContext;

namespace GoltaraSolutions.SpaWeb.Web.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class OrigemController : BaseController
    {
        private OrigemDomainServices sv;
        private IMapper _mapp;
        public OrigemController(OrigemDomainServices OrigemDomainServices)
        {
            sv = OrigemDomainServices;

            MapperConfiguration config = new MapperConfiguration(cfg =>
           {
               cfg.CreateMap<OrigemViewModel, OrigemModel>();
               cfg.CreateMap<OrigemModel, OrigemViewModel>()
                .ForMember(dest => dest.Ativo, opt => opt.MapFrom(src => (!src.Deletado).ToCustomString())); ;
           });

            _mapp = config.CreateMapper();
        }
        // GET: Origem
        public ActionResult Index(string tipo)
        {
            List<OrigemModel> listModel = sv.List(UsuarioLogado.IdEmpresa).ToList();
            List<OrigemViewModel> listView = new List<OrigemViewModel>();

            switch (tipo)
            {
                case "Ativos":
                    listModel = listModel.Where(i => i.Deletado == false).ToList();
                    ViewBag.Filtro = "Ativos";

                    break;
                case "Inativos":
                    listModel = listModel.Where(i => i.Deletado == true).ToList();
                    ViewBag.Filtro = "Inativos";

                    break;
                case "Todos":
                    listModel = listModel.ToList();
                    ViewBag.Filtro = "Todos";

                    break;
                default:
                    listModel = listModel.Where(i => i.Deletado == false).ToList();
                    ViewBag.Filtro = "Ativos";

                    break;
            }

            listModel.ForEach(x => listView.Add(_mapp.Map<OrigemViewModel>(x)));

            return View(listView);
        }

        // GET: Origem/Details/5
        public ActionResult Details(long id)
        {
            OrigemModel origem = sv.Find(id);

            return View(_mapp.Map<OrigemViewModel>(origem));
        }

        // GET: Origem/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Origem/Create
        [HttpPost]
        public ActionResult Create(OrigemViewModel objeto)
        {
            try
            {

                
                sv.Cadastrar(UsuarioLogado.IdEmpresa, objeto.Nome);

                TempData["Nome"] = objeto.Nome;
                TempData["Acao"] = "criado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Create();
            }
        }

        // GET: Origem/Edit/5
        public ActionResult Edit(long id)
        {
            OrigemModel origem = sv.Find(id);

            return View(_mapp.Map<OrigemViewModel>(origem));
        }

        // POST: Origem/Edit/5
        [HttpPost]
        public ActionResult Edit(long id, OrigemViewModel objeto)
        {
            try
            {
                
                sv.Editar(id, objeto.Nome);

                TempData["Nome"] = objeto.Nome;
                TempData["Acao"] = "editado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Edit(id);
            }
        }

        // GET: Origem/Delete/5
        public ActionResult Delete(long id)
        {
            OrigemModel origem = sv.Find(id);

            return View(_mapp.Map<OrigemViewModel>(origem));
        }

        // POST: Origem/Delete/5
        [HttpPost]
        public ActionResult Delete(long id, OrigemViewModel objeto)
        {
            try
            {
                
                sv.Delete(id);

                OrigemModel o = sv.Find(id);
                TempData["Nome"] = o.Nome;
                TempData["Acao"] = "desativado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View();
            }
        }

        // GET: Origem/Recover/5
        public ActionResult Recover(long id)
        {
            OrigemModel origem = sv.Find(id);

            return View(_mapp.Map<OrigemViewModel>(origem));
        }

        // POST: Origem/Recover/5
        [HttpPost]
        public ActionResult Recover(long id, OrigemViewModel objeto)
        {
            try
            {
                
                sv.Recover(id);

                OrigemModel o = sv.Find(id);
                TempData["Nome"] = o.Nome;
                TempData["Acao"] = "ativado";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View();
            }
        }
    }
}

GoltaraSoft.SpaWeb.Web/Views/Origem/Create.cshtml
@model GoltaraSolutions.SpaWeb.Web.Models.OrigemViewModel

@{
    ViewBag.Title = "Novo Canal";
}
<section class="content-header">
    <h1 class="box-title">
        @ViewBag.Title
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-default">
                @using (Html.BeginForm())
                {
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-12">
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary("", new { @class = "alert-danger", @role = "alert" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6 col-lg-6 col-xs-12">
                                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "label-action" })
                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", data_toggle = "tooltip", data_placement = "bottom", title = "Nome do Canal" } })
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="row">
                            <div class="col-md-12">
                                <a href="@Url.Action("Index")" class="btn btn-default btn-sm"><i class="fa fa-arrow-left"></i> Voltar</a>
                                <button type="submit" class="btn btn-primary btn-sm pull-right"><i class="fa fa-save"></i> Salvar</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

GoltaraSoft.SpaWeb.Web/Views/Origem/Details.cshtml
@model GoltaraSolutions.SpaWeb.Web.Models.OrigemViewModel

@{
    ViewBag.Title = Model.Nome;
}
<section class="content-header">
    <h1 class="box-title">
        @Html.Label(Model.Nome)
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-default">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Nome, new { @class = "label-detail" })
                                @Html.DisplayFor(m => m.Nome)
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Ativo, new { @class = "label-detail" })
                                @Html.DisplayFor(m => m.Ativo)
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <a href="@Url.Action("Index")" class="btn btn-default btn-sm pull-left"><i class="fa fa-arrow-left"></i> Voltar</a>
                                <span class="pull-right">
                                    @{ if (Model.Ativo == "Sim")
                                        {
                                            <a href="#" data-toggle="modal" data-target="#modalDelete" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Desativar</a>
                                        }
                                    }
                                    @{ if (Model.Ativo == "Sim")
                                        {
                                            <a href="@Url.Action("Edit","Origem", new { @id = Model.Id } )" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Editar</a>
                                        }
                                    }
                                    @{ if (Model.Ativo != "Sim")
                                        {
                                            <a href="#" data-toggle="modal" data-target="#modalRecover" class="btn btn-success btn-sm"><i class="fa fa-undo"></i> Ativar</a>
                                        }
                                    }
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Modal de Desativação -->
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Desativar Canal</h4>
            </div>
            @using (Html.BeginForm("Delete", "Origem", new { @id = Model.Id }, FormMethod.Post, new { @class = "form-horizontal", @role = "form" }))
            {
                <div class="modal-body">
                    <div class="form-group">
                        <div class="col-md-12">
                            <p>Você tem certeza que deseja <b>desativar</b> o canal <b>@Model.Nome</b> ?</p>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary pull-right">Confirmar</button>
                </div>
            }
        </div>
    </div>
</div>

<!-- Modal de Ativa -->
<div class="modal fade" id="modalRecover" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Ativar Canal</h4>
            </div>
            @using (Html.BeginForm("Recover", "Origem", new { @id = Model.Id }, FormMethod.Post, new { @class = "form-horizontal", @role = "form" }))
            {
                <div class="modal-body">
                    <div class="form-group">
                        <div class="col-md-12">
                            <p>Você tem certeza que deseja <b>ativar</b> o canal <b>@Model.Nome</b> ?</p>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary pull-right">Confirmar</button>
                </div>
            }
        </div>
    </div>
</div>

GoltaraSoft.SpaWeb.Web/Views/Origem/Edit.cshtml
@model GoltaraSolutions.SpaWeb.Web.Models.OrigemViewModel

@{
    ViewBag.Title = "Editar - " + Model.Nome;
}
<section class="content-header">
    <h1 class="box-title">
        @ViewBag.Title
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-default">
                @using (Html.BeginForm())
                {
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-12">
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary("", new { @class = "alert-danger", @role = "alert" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6 col-lg-6 col-xs-12">
                                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "label-action" })
                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", data_toggle = "tooltip", data_placement = "bottom", title = "Nome do Canal" } })
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="row">
                            <div class="col-md-12">
                                <a href="@Url.Action("Index")" class="btn btn-default btn-sm"><i class="fa fa-arrow-left"></i> Voltar</a>
                                <button type="submit" class="btn btn-primary btn-sm pull-right"><i class="fa fa-save"></i> Salvar</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

GoltaraSoft.SpaWeb.Web/Views/Origem/Index.cshtml
@model IEnumerable<GoltaraSolutions.SpaWeb.Web.Models.OrigemViewModel>

@{
    ViewBag.Title = "Canais de Divulgação";
}
<section class="content-header">
    <h1 class="box-title">
        @ViewBag.Title
        <small>Formas de um cliente conhecer a sua empresa.</small>
    </h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default">
                <div class="box-header">
                    @if (TempData["Acao"] != null && !string.IsNullOrWhiteSpace(TempData["Acao"].ToString()))
                    {
                        <div class="alert alert-dismissible alert-success">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            Muito bem! <strong>@TempData["Nome"].ToString()</strong> foi @TempData["Acao"].ToString() com sucesso.
                        </div>
                    }
                    <div class="float-none form-group">
                        <span class="">
                            <a href="@Url.Action("Create")" class="btn btn-default btn-sm">
                                <i class="fa fa-plus" aria-hidden="true"></i>
                                Novo
                            </a>
                        </span>
                        <div class="pull-right">
                            <span class="label-filter">
                                <i class="fa fa-filter" aria-hidden="true"></i>
                                <label>@ViewBag.Filtro</label>
                            </span>
                            <a class="btn btn-default btn-sm" role="button" data-toggle="collapse" href="#collapseFiltros" aria-expanded="false" aria-controls="collapseExample">
                                <i class="fa fa-search"></i>
                                Filtros
                            </a>
                        </div>
                    </div>

                    <div class="collapse" id="collapseFiltros">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    Filtros
                                </h3>
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="btn-group">
                                            @Html.ActionLink("Ativos", "Index", "Origem", new { @tipo = "Ativos" }, new { @class = "btn btn-success btn-sm" })
                                            @Html.ActionLink("Inativos", "Index", "Origem", new { @tipo = "Inativos" }, new { @class = "btn btn-primary btn-sm" })
                                            @Html.ActionLink("Todos", "Index", "Origem", new { @tipo = "Todos" }, new { @class = "btn btn-default btn-sm" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table table-striped table-hover display responsive nowrap" id="dataTable" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Nome)</th>
                                <th>@Html.DisplayNameFor(model => model.Ativo)</th>
                                <th class="text-center col-md-2">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr class="odd gradeX">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Nome)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Ativo)
                                    </td>
                                    <td class="text-center h4">
                                        <div class="row">
                                            <div class="col-md-6 col-xs-6">
                                                <span class="ficon">
                                                    <a href="@Url.Action("Details", "Origem", new { id = item.Id })">
                                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                                    </a>
                                                </span>
                                            </div>
                                            <div class="col-md-6 col-xs-6">
                                                @if (!item.Deletado)
                                                {
                                                    <span class="ficon">
                                                        <a href="@Url.Action("Edit", "Origem", new { id = item.Id })">
                                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                                        </a>
                                                    </span>
                                                }
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts {
    @Styles.Render("~/Content/datatables-css")
    @Scripts.Render("~/bundles/moment-js")
    @Scripts.Render("~/bundles/datatables-js")
}